group: edge

language: node_js

node_js:
  - 6
  - 7
  - 8

install: true

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt update
  - sudo apt install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

before_script:
  - npm i -g yarn
  - yarn global add npm-check-updates

script:
  - export ROOT=$PWD
  - >
    for path in 10-iron-pages \
                09-toolbar \
                08-core-icons \
                07-DOM-and-lifecycle \
                06-dom-repeat-and-filter \
                05-scoped-styles \
                04-content \
                03-observables \
                02-computed-properties \
                01-data-binging \
                0-template-2 \
                0-template; do

      export TARGET="$ROOT/$path"
      cd $TARGET
      yarn predeploy
      if [ -f npm-debug.log ]; then cat npm-debug.log; fi
      ncu -u
      yarn upgrade

    done;

cache:
  directories:
    - node_modules/
    - $HOME/.npm
